version: "3.4"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Bra!nb3yDevel0per"
      MSSQL_PID: "Express"
    ports:
      - "1412:1433"